name = "HiNoon"
author = "Verbina29"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7fd2c32471c4cf3a87ba6fe3f00af312c8d81f5addb3e2a7c3c52f6a542ec78"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2"
