name = "HiNoon"
author = "Verbina29"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "214e39ba6bad2f7b0306273917b5b00f7c2a4018285af7e38eb59f0959e6dc81"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2"
