name = "HiNoon"
author = "Verbina29"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3972ea75bc548ce268100d3e4ce4fb2dbaf65ab0cfbee86377ea19fcd37ed345"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2"
