name = "HiNoon"
author = "Verbina29"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c46bc500deb98ba24edc62ff82e7b154987e4b9823697cd1f23ee42f2bc6653"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2"
