name = "HiNoon"
author = "Verbina29"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb3d9897b5dc6d2956f472c4a7aed081795207c25498e0b169cdf67079d8acf3"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
