name = "HiNoon"
author = "Verbina29"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f58bc179192d16919c645511e28f37fd7b818fa8ac7f8d7a1686b8a0a7e0ec75"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2"
