name = "HiNoon"
author = "Verbina29"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6451fae77afbcdefeb7bbc6a2290c5e6ce245a26248d610f89cdb1736911dec"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
